### ISSUE TITLE
Gemfile modification doesn't handle gemfiles in subdirectories

### ISSUE THREAD

**Issue by jeremyevans** [ioquatix/bake-test-external#6]
My guess is `path` is relative to the gemfile location, and if the gemfile is in a subdirectory, you would need `../../..` (or something).  It's probably safer to determine the absolute path to the current directory, and pass that instead of trying to calculate an appropriate relative path.

Found when trying to add Grape as an external test to Rack, by adding the following to Rack's `config/external.yaml`

```
grape:
  url: https://github.com/ruby-grape/grape
  command: bundle exec rspec --exclude-pattern=spec/integration/**/*_spec.rb
  gemfile: gemfiles/rack_3_1.gemfile
```

Unrelated to this, but probably also a bug, is that failures due to bad gemfile or missing command are not reported as errors in CI.  See https://github.com/jeremyevans/rack/actions/runs/9539758130/job/26290479234 , where it doesn't even execute grape's tests due to errors, but still reports CI is passing.
